# docker-compose.yml
version: "0.1"

services:
  app:
    build: .
    command: uvicorn assistant.app.app:app --host 0.0.0.0 --port 9000
    env_file: assistant/.env
    volumes:
      - .:/app
    restart: always

  tg_app:
    build: .
    command: python assistant/app/tg_app.py
    env_file: assistant/.env
    volumes:
      - .:/app
    restart: always